services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_ProyectoBD
    ports:
      - "1423:1433" # <--- Mi recomendación para evitar conflictos
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Contra123! 
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: