<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MoodPet.Domain\MoodPet.Domain.csproj" />
    <ProjectReference Include="..\MoodPet.Infraestructure\MoodPet.Infraestructure.csproj" />
  </ItemGroup>

</Project>
